import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "CryptoArt",
  description: "Generated by CryptoArt Company",
  icons: {
    icon: "/images/logo-bg.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
